# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore AppWithTests/AppWithTests.csproj
        dotnet restore AppWithTestsTests/AppWithTestsTests.csproj
    - name: Build
      run: dotnet build AppWithTests/AppWithTests.csproj --no-restore
    - name: Test
      run: dotnet test AppWithTestsTests/AppWithTestsTests.csproj --no-build --verbosity detailed
    
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-artifact
        path: |
          AppWithTests/bin/
